version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${FRONTEND_VITE_API_URL:-""}
        - VITE_STANDARD_MODE_DAYS=${STANDARD_MODE_DAYS:-7}
    ports:
      - "8000:8000"
    environment:
      - EVENTS_DIR=${EVENTS_DIR:-/app/data/events}
    env_file:
      - .env
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped
