version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_STANDARD_MODE_DAYS=${STANDARD_MODE_DAYS:-7}
    expose:
      - "8000"
    networks:
      - web_gateway
    environment:
      - EVENTS_DIR=${EVENTS_DIR:-/app/data/events}
    env_file:
      - .env
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped

networks:
  web_gateway:
    external: true # 建议先手动创建：docker network create web_gateway
